### ISSUE TITLE
How do create custom multi-select filter class?

### ISSUE THREAD

**Issue by Derek-NCX** [JobDoesburg/django-admin-multi-select-filter#3]
I am trying to make a custom multiselect filter.  I have a code skeleton that looks like:

```
class MyCustomMultiSelectTypeFilter(MultiSelectFieldListFilter):
    title = "Title"

    def lookups(self, request, model_admin):
        return [
            (True, "Is Government"),
            (True, "Is private")
        ]

    def queryset(self, request, queryset):
        pass
```

I'm getting:

`line 483, in get_fields_from_path
    pieces = path.split(LOOKUP_SEP)
TypeError: 'str' object is not callable`

Instantiating it like this in the model admin class:

`list_filter = (
        (MyCustomMultiSelectTypeFilter, MultiSelectFieldListFilter),
    )`
    
    
   What do I need to add?

**Comment by JobDoesburg** [comment]
> `list_filter = ( (MyCustomMultiSelectTypeFilter, MultiSelectFieldListFilter), )`

should probably become 

`list_filter = ( ("field_name", MyCustomMultiSelectTypeFilter), )`

with `"field_name"` being the name of the field you want to filter on.

if you want implement your own logic, you should just include `MyCustomMultiSelectTypeFilter ` as `list_filter = (MyCustomMultiSelectTypeFilter,)`
