### ISSUE TITLE
it has problem in django 5.0.4

### ISSUE THREAD

**Issue by shyang0411** [JobDoesburg/django-admin-multi-select-filter#5]
There is an error in Python 3.11 and Django 5.0.4. 
When using MultiSelectRelatedFieldListFilter, an error occurs when the selected field is split as a list rather than a string.

**Comment by sangiovannidev** [comment]
I can confirm this issue, same result here with Django 5.0.6.

**Comment by shyang0411** [comment]
> I can confirm this issue, same result here with Django 5.0.6.

I copied this code into my application and modified it. 
After performing a type check, the logic to pass if it was a string and process it as an array if it was an array was processed separately.

**Comment by JobDoesburg** [comment]
I see, Django 5.0 changed the behaviour slightly. I have created a fix!
